"""Add document versioning: document_key and is_current

Revision ID: 0c8ae1d34f18
Revises: 3c35b133f327
Create Date: 2026-09-17 20:18:26.159336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ae1d34f18'
down_revision: Union[str, Sequence[str], None] = '3c35b133f327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('documents', sa.Column('document_key', sa.String(length=255), nullable=True))
    # server_default backfills every existing document to `is_current=True` —
    # correct on its own terms, since a document that predates versioning has
    # no history to be superseded by and is trivially its own current version.
    # Dropped immediately after: the app always sets this explicitly on
    # insert (see document_service.upload_document), and leaving a server
    # default in place would silently paper over a future insert that forgot
    # to.
    op.add_column(
        'documents',
        sa.Column('is_current', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('documents', 'is_current', server_default=None)
    op.create_index('uq_documents_current_version_per_key', 'documents', ['collection_id', 'document_key'], unique=True, postgresql_where=sa.text('is_current AND document_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_documents_current_version_per_key', table_name='documents', postgresql_where=sa.text('is_current AND document_key IS NOT NULL'))
    op.drop_column('documents', 'is_current')
    op.drop_column('documents', 'document_key')
    # ### end Alembic commands ###
