"""Add raw_content to documents for async ingestion

Revision ID: 3787b646d8d9
Revises: d3d443517615
Create Date: 2026-09-23 22:29:06.647988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3787b646d8d9'
down_revision: Union[str, Sequence[str], None] = 'd3d443517615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_content')
    # ### end Alembic commands ###
