"""Add retrieval golden examples and benchmark runs

Revision ID: 3c35b133f327
Revises: dc4e05b98a48
Create Date: 2026-09-17 20:08:45.915572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c35b133f327'
down_revision: Union[str, Sequence[str], None] = 'dc4e05b98a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_benchmark_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('cases', sa.Integer(), nullable=False),
    sa.Column('mean_recall', sa.Float(), nullable=False),
    sa.Column('mrr', sa.Float(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_benchmark_runs_collection_time', 'retrieval_benchmark_runs', ['collection_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_benchmark_runs_tenant_id'), 'retrieval_benchmark_runs', ['tenant_id'], unique=False)
    op.create_table('retrieval_golden_examples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('relevant_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'query', name='uq_golden_example_collection_query')
    )
    op.create_index(op.f('ix_retrieval_golden_examples_collection_id'), 'retrieval_golden_examples', ['collection_id'], unique=False)
    op.create_index(op.f('ix_retrieval_golden_examples_tenant_id'), 'retrieval_golden_examples', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_golden_examples_tenant_id'), table_name='retrieval_golden_examples')
    op.drop_index(op.f('ix_retrieval_golden_examples_collection_id'), table_name='retrieval_golden_examples')
    op.drop_table('retrieval_golden_examples')
    op.drop_index(op.f('ix_retrieval_benchmark_runs_tenant_id'), table_name='retrieval_benchmark_runs')
    op.drop_index('ix_retrieval_benchmark_runs_collection_time', table_name='retrieval_benchmark_runs')
    op.drop_table('retrieval_benchmark_runs')
    # ### end Alembic commands ###
