"""Scope documents to collections

Revision ID: 78dba2d61f49
Revises: c7aff6d7cff9
Create Date: 2026-07-28 20:50:48.312309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dba2d61f49'
down_revision: Union[str, Sequence[str], None] = 'c7aff6d7cff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('collection_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.create_index(op.f('ix_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_foreign_key('fk_documents_collection_id', 'documents', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_documents_collection_id', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_collection_id'), table_name='documents')
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.drop_column('documents', 'collection_id')
    # ### end Alembic commands ###
