"""Add rolling conversation summary

Revision ID: dc4e05b98a48
Revises: e35717194db3
Create Date: 2026-08-17 15:24:45.721157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4e05b98a48'
down_revision: Union[str, Sequence[str], None] = 'e35717194db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summary_through_seq', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary_through_seq')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
