"""Record what the platform judged about a turn it already served

Revision ID: e35717194db3
Revises: f829fbc500f9
Create Date: 2026-08-01 10:43:54.192398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e35717194db3'
down_revision: Union[str, Sequence[str], None] = 'f829fbc500f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turn_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('evaluator', sa.String(length=32), nullable=False),
    sa.Column('rubric_version', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_top_score', sa.Float(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('judge_model', sa.String(length=63), nullable=True),
    sa.Column('judge_provider', sa.String(length=31), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'evaluator', 'rubric_version', name='uq_turn_evaluations_message_rubric')
    )
    op.create_index('ix_turn_evaluations_agent_time', 'turn_evaluations', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_turn_evaluations_tenant_id'), 'turn_evaluations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_evaluations_tenant_id'), table_name='turn_evaluations')
    op.drop_index('ix_turn_evaluations_agent_time', table_name='turn_evaluations')
    op.drop_table('turn_evaluations')
    # ### end Alembic commands ###
