"""register mcp servers as tenant-scoped configuration

Note the columns that are not here. There is no `command`/`args` pair, because
launching an MCP server as a subprocess would make this table tenant-configurable
command execution on the platform's own hosts. And `auth_token_encrypted` holds
Fernet ciphertext rather than a plaintext token or a hash: the credential belongs
to a third party and has to be replayed on every call, so it can be neither
hashed nor stored readable.

Revision ID: f829fbc500f9
Revises: c8761c7391cd
Create Date: 2026-07-30 05:23:59.742012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f829fbc500f9'
down_revision: Union[str, Sequence[str], None] = 'c8761c7391cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=31), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('auth_token_encrypted', sa.Text(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_mcp_server_tenant_slug')
    )
    op.create_index(op.f('ix_mcp_servers_slug'), 'mcp_servers', ['slug'], unique=False)
    op.create_index(op.f('ix_mcp_servers_tenant_id'), 'mcp_servers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_servers_tenant_id'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_slug'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
